### ISSUE TITLE
 [NB-Create-Archive]TaskListener Initialization improper - constructor parameters not assigned to fields. Works well in debug

### ISSUE THREAD

**Issue by manikantannaren** [manikantannaren/mynetbeans#1]
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.apache.tools.ant.module.run.TargetExecutor$WrapperExecutorTask
java.lang.NullPointerException
    at org.openide.filesystems.FileUtil.toFile(FileUtil.java:829)
    at org.openide.filesystems.FileUtil.getFileDisplayName(FileUtil.java:1489)
    at org.pr.nb.zip.AddToFavoritesConfirmPanel.<init>(AddToFavoritesConfirmPanel.java:47)
    at org.pr.nb.zip.ArchiverAntScriptCompletionTaskListener.taskFinished(ArchiverAntScriptCompletionTaskListener.java:51)
    at org.openide.util.Task.notifyFinished(Task.java:240)
    at org.openide.util.Task.run(Task.java:260)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused: org.openide.util.RequestProcessor$SlowItem: task failed due to
    at org.openide.util.RequestProcessor.post(RequestProcessor.java:419)
    at org.apache.tools.ant.module.run.TargetExecutor.execute(TargetExecutor.java:396)
    at org.apache.tools.ant.module.api.AntTargetExecutor.execute(AntTargetExecutor.java:112)
    at org.apache.tools.ant.module.api.support.ActionUtils.runTarget(ActionUtils.java:125)
    at org.apache.tools.ant.module.api.support.ActionUtils.runTarget(ActionUtils.java:91)
    at org.pr.nb.zip.ArchiveCreator.run(ArchiveCreator.java:93)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[catch] at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
INFO [org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater]: Resolving dependencies took: 17 ms

**Comment by manikantannaren** [comment]
Dependent on the behaviour of the ActionUtil class.
