### ISSUE TITLE
[NB-Generate-SUID] Netbeans 11.1 java.lang.LinkageError

### ISSUE THREAD

**Issue by ColdanR** [manikantannaren/mynetbeans#36]
**Product Version:** Apache NetBeans IDE 11.1
**Java:** 11.0.4-ojdkbuild; OpenJDK 64-Bit Server VM 11.0.4-ojdkbuild+11-LTS
**Runtime:** OpenJDK Runtime Environment 11.0.4-ojdkbuild+11-LTS
**System:** Windows 10 version 10.0 running on amd64; Cp1252; de_DE (nb)

Looks like an error at the module system of java.

```
java.lang.LinkageError: loader constraint violation: loader org.netbeans.StandardModule$OneModuleClassLoader @79732e6d wants to load interface com.sun.source.tree.CompilationUnitTree. A different interface with the same name was previously loaded by org.netbeans.StandardModule$OneModuleClassLoader @16e85f90. (com.sun.source.tree.CompilationUnitTree is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @16e85f90, parent loader 'app')
	at org.pr.nb.suid.SUIDGenCancellableTask.run(SUIDGenCancellableTask.java:48)
	at org.pr.nb.suid.SUIDGenCancellableTask.run(SUIDGenCancellableTask.java:28)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:673)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:663)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:502)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:130)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:114)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:81)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:452)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:423)
	at org.netbeans.api.java.source.JavaSource.runModificationTask(JavaSource.java:684)
	at org.pr.nb.suid.RandomSUIDGenerator.invoke(RandomSUIDGenerator.java:56)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel.invokeSelected(GenerateCodePanel.java:165)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel.listMouseReleased(GenerateCodePanel.java:109)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel.access$000(GenerateCodePanel.java:41)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel$2.mouseReleased(GenerateCodePanel.java:85)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by viper-bvu** [comment]
### Same bug with Netbeans 11.3 / openJDK 13.0.2:

**Product Version         = Apache NetBeans IDE 11.3
Operating System        = Windows 10 version 10.0 running on amd64
Java; VM; Vendor        = 13.0.2; OpenJDK 64-Bit Server VM 13.0.2+8; Oracle Corporation
Runtime                 = OpenJDK Runtime Environment 13.0.2+8**
  

java.lang.LinkageError: loader constraint violation: loader org.netbeans.StandardModule$OneModuleClassLoader @36c2b91a wants to load interface com.sun.source.tree.CompilationUnitTree. A different interface with the same name was previously loaded by org.netbeans.StandardModule$OneModuleClassLoader @6cbc5f31. (com.sun.source.tree.CompilationUnitTree is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @6cbc5f31, parent loader 'app')
	at org.pr.nb.suid.SUIDGenCancellableTask.run(SUIDGenCancellableTask.java:48)
	at org.pr.nb.suid.SUIDGenCancellableTask.run(SUIDGenCancellableTask.java:28)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:673)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:663)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:502)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:130)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:114)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:81)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:452)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:423)
	at org.netbeans.api.java.source.JavaSource.runModificationTask(JavaSource.java:684)
	at org.pr.nb.suid.RandomSUIDGenerator.invoke(RandomSUIDGenerator.java:56)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel.invokeSelected(GenerateCodePanel.java:165)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel.listKeyPressed(GenerateCodePanel.java:121)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel.access$200(GenerateCodePanel.java:41)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel$4.keyPressed(GenerateCodePanel.java:95)
	at java.desktop/java.awt.AWTEventMulticaster.keyPressed(AWTEventMulticaster.java:258)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6594)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2849)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4893)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ilgrosso** [comment]
Same with Netbeans 12.2, as it seems: see #41

**Comment by manikantannaren** [comment]
Sorry for the delay. 

When I tried NB 12.2 and OpenJDK 11;  without the nb-javac plugin; nb-javac is not needed for java 11.
I don't see any exceptions and the code is generated properly.
@ilgrosso  @ColdanR  @viper-bvu Can you please confirm if you installed and enabled nb-javac?

**Comment by manikantannaren** [comment]
Works wth the following setup
Product Version: Apache NetBeans IDE 12.2
Java: 11.0.6; OpenJDK 64-Bit Server VM 11.0.6+10
Runtime: OpenJDK Runtime Environment 11.0.6+10
**NB-javac** not installed

**Comment by ColdanR** [comment]
I have nb-javac installed. Didn't check it with NetBeans 12.2

**Comment by ilgrosso** [comment]
I have nb-javac installed.
Netbeans 12.2, OpenJDK 11.0.9.1, Linux

**Comment by ilgrosso** [comment]
I confirm it works after removing `nb-javac`: mainly using Java 11+ but sometimes 8: resulting setup not very convenient, any chance to fix?

**Comment by manikantannaren** [comment]
Fixed issue. @ilgrosso @ColdanR @viper-bvu Please use org-pr-nb-suid.nbm from testrel folder (https://github.com/manikantannaren/mynetbeans/blob/master/test-rel/java11/org-pr-nb-suid.nbm) . I will be much obliged if you can test and provide feedback. If everything is good, I will create a release whileI will figure out the publishing of plugin for Apache NetBeans

**Comment by ilgrosso** [comment]
@manikantannaren shall I do something particular to activate the plugin after installation? Even with Netbeans restart, the popup dialog for a `Serializable` class without `serialVersionUID` defined keeps me proposing either to generate the default value or to suppress warnings.
I did try with Netbeans 12.4 on Linux with AdoptOpenJDK 11

**Comment by manikantannaren** [comment]
The plugin does not modify the existing hint. it provides a insert code completion action.
Press Ctrl+I on mac or Right click in editor -> Insert code popup menu to see the options.

<img width="204" alt="image" src="https://user-images.githubusercontent.com/5435047/122751540-83f55280-d2ad-11eb-897f-1cea75364d14.png">

After choosing
<img width="506" alt="image" src="https://user-images.githubusercontent.com/5435047/122751288-32e55e80-d2ad-11eb-965e-d20ae62bc022.png">

**Comment by ilgrosso** [comment]
Thanks for clarification: it works like a charm then! :+1:

**Comment by ilgrosso** [comment]
One thing: when attempting to insert into anonymous inner classes, insertion is actually happening in the parent class.
Also, couldn't it be nicer to *replace* the existing value, if found?

**Comment by manikantannaren** [comment]
Anonymous class are problematic for serialization and the case where it may be applicable is
`new Serializable() { ....serializable fields ....}`  
So this does not seem to merit the effort. But the second case, updating an existing value I think can be done as an enhancement
