### ISSUE TITLE
MissingResourceException on click on the toolbutton

### ISSUE THREAD

**Issue by Chris2011** [manikantannaren/mynetbeans#4]
I opened netbeans, a project is selected and a file is open. I'm with my cursor inside the file. I see the toolbar icon is enabled. When I click on the icon, I got this exception.

``` Java
java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key WIZARD_TITLE
    at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
    at java.util.ResourceBundle.getString(ResourceBundle.java:407)
    at org.openide.util.NbBundle.getMessage(NbBundle.java:642)
    at org.pr.nb.zip.Bundle.WIZARD_TITLE(Bundle.java:25)
    at org.pr.nb.zip.ArchiverAction.actionPerformed(ArchiverAction.java:82)
[catch] at org.openide.awt.InjectorAny.actionPerformed(InjectorAny.java:73)
    at org.openide.awt.ContextAction$Performer.actionPerformed(ContextAction.java:226)
    at org.openide.awt.ContextManager.actionPerformed(ContextManager.java:260)
    at org.openide.awt.ContextAction.actionPerformed(ContextAction.java:109)
    at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:93)
    at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
    at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
    at org.openide.awt.GeneralAction$BaseDelAction.actionPerformed(GeneralAction.java:234)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Maybe it is better to disable the button, when I don't have selected a file/folder, only have an open file with a cursor inside.

The other problem is, that when I try to export a file or a folder to an archive with your plugin on the favorite window, I got the same exception. Have the newest update from your plugin.

Regards

Chris

**Comment by manikantannaren** [comment]
I fixed the problem by doing a clean build. 
The problem cropped  due to an improper build. I am not sure but may be due to the fact that I use an external USB storage for my projects and my netbeans userdir is also on that drive. Can't say for sure.
I have created a new NBM and uploaded it to [Netbeans plugin portal](http://plugins.netbeans.org/plugin/58976/?show=true)

**Comment by Chris2011** [comment]
Seems to be working now, thx. Only one thing, you've forgotten to update the version maybe to 2.0.2 because I had to uninstall it but I don't care. Only for your information. Is it correct, that there is no entry inside the context menu or a shortcut? It is keyboard friendly to have this. Should I create a new ticket for this?

**Comment by manikantannaren** [comment]
I agree about the context menu. The folders are easy to handle (folders/any) but the file types are the ones that concern me most. Since I will have to add all mime-types. I am checking the feasibility of a system wide action.

**Comment by manikantannaren** [comment]
Yes please! Create a new ticket for the context menu.
